# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Spooky Action
tagline:          'Spooky Action ART'
description:      'Bob Ross meets Fantasia in this live drawing musical experience. Comics artist <a href="http://elkpapa.party" target="_blank">Elk Paauw</a> and composer <a href="http://andrewolmstead.com" target="_blank">Andrew Olmstead</a> combine mediums to tell stories.'
url:              https://aolmstead.github.io/spooky-action-blog/
baseurl:          https://aolmstead.github.io/spooky-action-blog/

author:
  name:           'Andrew Olmstead'
  url:            https://andrewolmstead.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/spooky-action-blog
